/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_tera_client_TeraMutationImpl */

#ifndef _Included_com_baidu_tera_client_TeraMutationImpl
#define _Included_com_baidu_tera_client_TeraMutationImpl
#pragma GCC visibility push(default)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_tera_client_TeraMutationImpl
 * Method:    nativeAdd
 * Signature: (J[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_tera_client_TeraMutationImpl_nativeAdd
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_baidu_tera_client_TeraMutationImpl
 * Method:    nativeDeleteRow
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_tera_client_TeraMutationImpl_nativeDeleteRow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_tera_client_TeraMutationImpl
 * Method:    nativeDeleteFamily
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_tera_client_TeraMutationImpl_nativeDeleteFamily
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_baidu_tera_client_TeraMutationImpl
 * Method:    nativeDeleteColumn
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_tera_client_TeraMutationImpl_nativeDeleteColumn
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_baidu_tera_client_TeraMutationImpl
 * Method:    nativeDeleteColumns
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_tera_client_TeraMutationImpl_nativeDeleteColumns
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#pragma GCC visibility pop
#endif
