/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_tera_client_TeraBase */

#ifndef _Included_com_baidu_tera_client_TeraBase
#define _Included_com_baidu_tera_client_TeraBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_tera_client_TeraBase
 * Method:    nativeInitGlog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_tera_client_TeraBase_nativeInitGlog
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_baidu_tera_client_TeraBase
 * Method:    nativeGlog
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_tera_client_TeraBase_nativeGlog
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_baidu_tera_client_TeraBase
 * Method:    nativeVlog
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_tera_client_TeraBase_nativeVlog
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
