/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_tera_client_TeraReaderImpl */

#ifndef _Included_com_baidu_tera_client_TeraReaderImpl
#define _Included_com_baidu_tera_client_TeraReaderImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_tera_client_TeraReaderImpl
 * Method:    nativeAddColumn
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_baidu_tera_client_TeraReaderImpl_nativeAddColumn(JNIEnv *, jobject, jlong, jbyteArray,
                                                          jbyteArray);

/*
 * Class:     com_baidu_tera_client_TeraReaderImpl
 * Method:    nativeAddFamily
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_baidu_tera_client_TeraReaderImpl_nativeAddFamily(JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_baidu_tera_client_TeraReaderImpl
 * Method:    nativeDeleteReader
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_baidu_tera_client_TeraReaderImpl_nativeDeleteReader(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
