# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='tera',
  serialized_pb=_b('\n\rmonitor.proto\x12\x04tera\"\x9b\x01\n\x0eMonitorRequest\x12\x14\n\x0ctera_zk_addr\x18\x01 \x01(\t\x12\x14\n\x0ctera_zk_root\x18\x02 \x01(\t\x12\x1a\n\x03\x63md\x18\x05 \x01(\x0e\x32\r.tera.CmdType\x12\x13\n\x0btabletnodes\x18\x06 \x03(\t\x12\x15\n\rmin_timestamp\x18\x07 \x01(\x04\x12\x15\n\rmax_timestamp\x18\x08 \x01(\x04\"\x85\x04\n\x0eTabletNodeStat\x12\x12\n\ntime_stamp\x18\x01 \x01(\x04\x12\x0c\n\x04load\x18\x02 \x01(\x04\x12\x14\n\x0ctablet_total\x18\x03 \x01(\r\x12\x15\n\rtablet_onbusy\x18\x04 \x01(\r\x12\x15\n\rlow_read_cell\x18\x0b \x01(\r\x12\x11\n\tscan_rows\x18\x0c \x01(\r\x12\x10\n\x08scan_kvs\x18\r \x01(\r\x12\x11\n\tscan_size\x18\x0e \x01(\r\x12\x11\n\tread_rows\x18\x0f \x01(\r\x12\x10\n\x08read_kvs\x18\x10 \x01(\r\x12\x11\n\tread_size\x18\x11 \x01(\r\x12\x12\n\nwrite_rows\x18\x12 \x01(\r\x12\x11\n\twrite_kvs\x18\x13 \x01(\r\x12\x12\n\nwrite_size\x18\x14 \x01(\r\x12\x10\n\x08mem_used\x18\x15 \x01(\x04\x12\x0e\n\x06net_tx\x18\x16 \x01(\r\x12\x0e\n\x06net_rx\x18\x17 \x01(\r\x12\x10\n\x08\x64\x66s_io_r\x18\x18 \x01(\r\x12\x10\n\x08\x64\x66s_io_w\x18\x19 \x01(\r\x12\x12\n\nlocal_io_r\x18\x1a \x01(\r\x12\x12\n\nlocal_io_w\x18\x1b \x01(\r\x12\x10\n\x08status_m\x18\x1f \x01(\t\x12\x15\n\rtablet_onload\x18  \x01(\r\x12\x16\n\x0etablet_onsplit\x18! \x01(\r\x12#\n\nextra_stat\x18( \x03(\x0b\x32\x0f.tera.ExtraStat\"C\n\x0fTabletNodeStats\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12\"\n\x04stat\x18\x02 \x03(\x0b\x32\x14.tera.TabletNodeStat\"(\n\tExtraStat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04\"O\n\x0fMonitorResponse\x12\x12\n\x06\x65rrmsg\x18\x01 \x01(\t:\x02ok\x12(\n\tstat_list\x18\x02 \x03(\x0b\x32\x15.tera.TabletNodeStats*/\n\x07\x43mdType\x12\t\n\x05kList\x10\x01\x12\x0b\n\x07kGetAll\x10\x02\x12\x0c\n\x08kGetPart\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='tera.CmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kList', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kGetAll', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kGetPart', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=893,
  serialized_end=940,
)
_sym_db.RegisterEnumDescriptor(_CMDTYPE)

CmdType = enum_type_wrapper.EnumTypeWrapper(_CMDTYPE)
kList = 1
kGetAll = 2
kGetPart = 3



_MONITORREQUEST = _descriptor.Descriptor(
  name='MonitorRequest',
  full_name='tera.MonitorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tera_zk_addr', full_name='tera.MonitorRequest.tera_zk_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tera_zk_root', full_name='tera.MonitorRequest.tera_zk_root', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='tera.MonitorRequest.cmd', index=2,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tabletnodes', full_name='tera.MonitorRequest.tabletnodes', index=3,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_timestamp', full_name='tera.MonitorRequest.min_timestamp', index=4,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_timestamp', full_name='tera.MonitorRequest.max_timestamp', index=5,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=179,
)


_TABLETNODESTAT = _descriptor.Descriptor(
  name='TabletNodeStat',
  full_name='tera.TabletNodeStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='tera.TabletNodeStat.time_stamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load', full_name='tera.TabletNodeStat.load', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tablet_total', full_name='tera.TabletNodeStat.tablet_total', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tablet_onbusy', full_name='tera.TabletNodeStat.tablet_onbusy', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_read_cell', full_name='tera.TabletNodeStat.low_read_cell', index=4,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scan_rows', full_name='tera.TabletNodeStat.scan_rows', index=5,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scan_kvs', full_name='tera.TabletNodeStat.scan_kvs', index=6,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scan_size', full_name='tera.TabletNodeStat.scan_size', index=7,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_rows', full_name='tera.TabletNodeStat.read_rows', index=8,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_kvs', full_name='tera.TabletNodeStat.read_kvs', index=9,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_size', full_name='tera.TabletNodeStat.read_size', index=10,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_rows', full_name='tera.TabletNodeStat.write_rows', index=11,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_kvs', full_name='tera.TabletNodeStat.write_kvs', index=12,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_size', full_name='tera.TabletNodeStat.write_size', index=13,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mem_used', full_name='tera.TabletNodeStat.mem_used', index=14,
      number=21, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net_tx', full_name='tera.TabletNodeStat.net_tx', index=15,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net_rx', full_name='tera.TabletNodeStat.net_rx', index=16,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dfs_io_r', full_name='tera.TabletNodeStat.dfs_io_r', index=17,
      number=24, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dfs_io_w', full_name='tera.TabletNodeStat.dfs_io_w', index=18,
      number=25, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_io_r', full_name='tera.TabletNodeStat.local_io_r', index=19,
      number=26, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_io_w', full_name='tera.TabletNodeStat.local_io_w', index=20,
      number=27, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_m', full_name='tera.TabletNodeStat.status_m', index=21,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tablet_onload', full_name='tera.TabletNodeStat.tablet_onload', index=22,
      number=32, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tablet_onsplit', full_name='tera.TabletNodeStat.tablet_onsplit', index=23,
      number=33, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra_stat', full_name='tera.TabletNodeStat.extra_stat', index=24,
      number=40, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=699,
)


_TABLETNODESTATS = _descriptor.Descriptor(
  name='TabletNodeStats',
  full_name='tera.TabletNodeStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='tera.TabletNodeStats.addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stat', full_name='tera.TabletNodeStats.stat', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=701,
  serialized_end=768,
)


_EXTRASTAT = _descriptor.Descriptor(
  name='ExtraStat',
  full_name='tera.ExtraStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tera.ExtraStat.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tera.ExtraStat.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=770,
  serialized_end=810,
)


_MONITORRESPONSE = _descriptor.Descriptor(
  name='MonitorResponse',
  full_name='tera.MonitorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='tera.MonitorResponse.errmsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("ok").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stat_list', full_name='tera.MonitorResponse.stat_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=812,
  serialized_end=891,
)

_MONITORREQUEST.fields_by_name['cmd'].enum_type = _CMDTYPE
_TABLETNODESTAT.fields_by_name['extra_stat'].message_type = _EXTRASTAT
_TABLETNODESTATS.fields_by_name['stat'].message_type = _TABLETNODESTAT
_MONITORRESPONSE.fields_by_name['stat_list'].message_type = _TABLETNODESTATS
DESCRIPTOR.message_types_by_name['MonitorRequest'] = _MONITORREQUEST
DESCRIPTOR.message_types_by_name['TabletNodeStat'] = _TABLETNODESTAT
DESCRIPTOR.message_types_by_name['TabletNodeStats'] = _TABLETNODESTATS
DESCRIPTOR.message_types_by_name['ExtraStat'] = _EXTRASTAT
DESCRIPTOR.message_types_by_name['MonitorResponse'] = _MONITORRESPONSE
DESCRIPTOR.enum_types_by_name['CmdType'] = _CMDTYPE

MonitorRequest = _reflection.GeneratedProtocolMessageType('MonitorRequest', (_message.Message,), dict(
  DESCRIPTOR = _MONITORREQUEST,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:tera.MonitorRequest)
  ))
_sym_db.RegisterMessage(MonitorRequest)

TabletNodeStat = _reflection.GeneratedProtocolMessageType('TabletNodeStat', (_message.Message,), dict(
  DESCRIPTOR = _TABLETNODESTAT,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:tera.TabletNodeStat)
  ))
_sym_db.RegisterMessage(TabletNodeStat)

TabletNodeStats = _reflection.GeneratedProtocolMessageType('TabletNodeStats', (_message.Message,), dict(
  DESCRIPTOR = _TABLETNODESTATS,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:tera.TabletNodeStats)
  ))
_sym_db.RegisterMessage(TabletNodeStats)

ExtraStat = _reflection.GeneratedProtocolMessageType('ExtraStat', (_message.Message,), dict(
  DESCRIPTOR = _EXTRASTAT,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:tera.ExtraStat)
  ))
_sym_db.RegisterMessage(ExtraStat)

MonitorResponse = _reflection.GeneratedProtocolMessageType('MonitorResponse', (_message.Message,), dict(
  DESCRIPTOR = _MONITORRESPONSE,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:tera.MonitorResponse)
  ))
_sym_db.RegisterMessage(MonitorResponse)


# @@protoc_insertion_point(module_scope)
